Added endpoints traffic stats monitoring to nodes
This tracks what IP addresses, ports, and protocols (tcp or udp) are
being monitored by services (with refcounting) and updates the
OpenVSwitch rules as appropriate to track the incoming traffic to
endpoints on the local node.

diff --git a/pkg/sdn/plugin/bin/openshift-sdn-ovs b/pkg/sdn/plugin/bin/openshift-sdn-ovs
--- a/pkg/sdn/plugin/bin/openshift-sdn-ovs
+++ b/pkg/sdn/plugin/bin/openshift-sdn-ovs
@@ -9,11 +9,14 @@ tenant_id=$3
 ingress_bw=$4
 egress_bw=$5
 macvlan=$6
+ip_addr=$7
+ip_protocol=$8
+ip_port=$9
 
 lockwrap() {
     (
-    flock 200
-    "$@"
+        flock 200
+        "$@"
     ) 200>${lock_file}
 }
 
@@ -31,24 +34,24 @@ get_veth_host() {
 get_ipaddr_pid_veth() {
     network_mode=$(docker inspect --format "{{.HostConfig.NetworkMode}}" ${net_container})
     if [ "${network_mode}" == "host" ]; then
-      # quit, nothing for the SDN here
-      exit 0
+        # quit, nothing for the SDN here
+        exit 0
     elif [[ "${network_mode}" =~ container:.* ]]; then
-      # Get pod infra container
-      net_container=$(echo ${network_mode} | cut -d ":" -f 2)
+        # Get pod infra container
+        net_container=$(echo ${network_mode} | cut -d ":" -f 2)
     fi
     pid=$(docker inspect --format "{{.State.Pid}}" ${net_container})
 
     ipaddr=$(docker inspect --format "{{.NetworkSettings.IPAddress}}" ${net_container})
     if [ -z "$ipaddr" ]; then
-	echo "Could not find IP address for container ${net_container}"
-	exit 1
+        echo "Could not find IP address for container ${net_container}"
+        exit 1
     fi
 
     veth_host=$(get_veth_host $pid)
     if [ -z "$veth_host" ]; then
-	echo "Could not find host veth interface for container ${net_container}"
-	exit 1
+        echo "Could not find host veth interface for container ${net_container}"
+        exit 1
     fi
 }
 
@@ -68,13 +71,14 @@ del_ovs_port() {
 add_ovs_flows() {
     ovs_port=$(ovs-vsctl get Interface ${veth_host} ofport)
     if [ -z "$ovs_port" ]; then
-	echo "Could not find OVS port for veth device ${veth_host} of container ${net_container}"
-	exit 1
+        echo "Could not find OVS port for veth device ${veth_host} of container ${net_container}"
+        exit 1
     fi
+
     macaddr=$(nsenter -n -t $pid -- ip link show dev eth0 | sed -n -e 's/.*link.ether \([^ ]*\).*/\1/p')
     if [ -z "$macaddr" ]; then
-	echo "Could not find MAC address for container ${net_container}"
-	exit 1
+        echo "Could not find MAC address for container ${net_container}"
+        exit 1
     fi
 
     # from container
@@ -86,10 +90,10 @@ add_ovs_flows() {
 
     # IP to container
     if [ $tenant_id = "0" ]; then
-	ovs-ofctl -O OpenFlow13 add-flow br0 "table=7, priority=100, ip, nw_dst=${ipaddr}, actions=output:${ovs_port}"
+        ovs-ofctl -O OpenFlow13 add-flow br0 "table=7, priority=100, ip, nw_dst=${ipaddr}, actions=load:${ovs_port}->NXM_NX_REG1[0..31], goto_table:8"
     else
-	ovs-ofctl -O OpenFlow13 add-flow br0 "table=7, priority=100, reg0=0, ip, nw_dst=${ipaddr}, actions=output:${ovs_port}"
-	ovs-ofctl -O OpenFlow13 add-flow br0 "table=7, priority=100, reg0=${tenant_id}, ip, nw_dst=${ipaddr}, actions=output:${ovs_port}"
+        ovs-ofctl -O OpenFlow13 add-flow br0 "table=7, priority=100, reg0=0, ip, nw_dst=${ipaddr}, actions=load:${ovs_port}->NXM_NX_REG1[0..31], goto_table:8"
+        ovs-ofctl -O OpenFlow13 add-flow br0 "table=7, priority=100, reg0=${tenant_id}, ip, nw_dst=${ipaddr}, actions=load:${ovs_port}->NXM_NX_REG1[0..31], goto_table:8"
     fi
 
     # Pod ingress == OVS bridge egress
@@ -112,6 +116,8 @@ del_ovs_flows() {
     ovs-ofctl -O OpenFlow13 del-flows br0 "arp,nw_dst=${ipaddr}"
     ovs-ofctl -O OpenFlow13 del-flows br0 "arp,nw_src=${ipaddr}"
 
+    # XXX Does the above dele the monitoring rules too?
+
     qos=$(ovs-vsctl get port ${veth_host} qos)
     if [ "$qos" != "[]" ]; then
         ovs-vsctl clear port ${veth_host} qos
@@ -131,41 +137,72 @@ ensure_subnet_route() {
 add_macvlan() {
     default_dev=$(ip route show | sed -ne 's/^default .* dev \([^ ]*\) .*/\1/p')
     if [ -z "$default_dev" ]; then
-	echo "Could not find default network interface"
-	exit 1
+        echo "Could not find default network interface"
+        exit 1
     fi
     ip link add link $default_dev name macvlan0 type macvlan mode private
     ip link set macvlan0 netns $pid
 }
 
+add_ovs_monitoring_flows() {
+    ovs-ofctl -O OpenFlow13 add-flow br0 "table=8, priority=100, ${ip_protocol}, nw_dst=${ip_addr}, ${ip_protocol}_dst=${ip_port}, actions=output:NXM_NX_REG1[0..31]"
+}
+
+del_ovs_monitoring_flows() {
+    ovs-ofctl -O OpenFlow13 del-flows br0 "table=8, ${ip_protocol}, nw_dst=${ip_addr}, ${ip_protocol}_dst=${ip_port}"
+}
+
+clear_ovs_monitoring_flows() {
+    # We need to wipe the table and then re-add the default rule
+    ovs-ofctl -O OpenFlow13 del-flows br0 "table=8"
+    ovs-ofctl -O OpenFlow13 add-flow br0 "table=8, priority=0, actions=output:NXM_NX_REG1[0..31]"
+}
+
 run() {
-    get_ipaddr_pid_veth
     source /run/openshift-sdn/config.env
 
     case "$action" in
-	setup)
-	    add_ovs_port
-	    add_ovs_flows
-	    add_subnet_route
-	    if [ "$macvlan" = true ]; then
-		add_macvlan
-	    fi
-	    ;;
+        setup)
+            get_ipaddr_pid_veth
+            add_ovs_port
+            add_ovs_flows
+            add_subnet_route
+            if [ "$macvlan" = true ]; then
+                add_macvlan
+            fi
+            ;;
 
-	update)
-	    ensure_ovs_port
-	    del_ovs_flows
-	    add_ovs_flows
-	    ensure_subnet_route
-	    ;;
+        update)
+            get_ipaddr_pid_veth
+            ensure_ovs_port
+            del_ovs_flows
+            add_ovs_flows
+            ensure_subnet_route
+            ;;
 
-	teardown)
-	    del_ovs_flows
-	    # Delete ovs port in the end, del_ovs_flows needs the port to delete qos record
-	    del_ovs_port
-	    ;;
+        teardown)
+            get_ipaddr_pid_veth
+            del_ovs_flows
+            # Delete ovs port in the end, del_ovs_flows needs the port to delete qos record
+            del_ovs_port
+            ;;
 
-	*)
+        monitor)
+            # Add monitoring to a port
+            add_ovs_monitoring_flows
+            ;;
+
+        unmonitor)
+            # Remove monitoring from a port
+            del_ovs_monitoring_flows
+            ;;
+
+        clearmonitoring)
+            # Remove monitoring from all ports
+            clear_ovs_monitoring_flows
+            ;;
+
+        *)
             echo "Bad input: $@"
             exit 1
     esac
